name: "Continuous Integration"

on:
  pull_request:
  push:

jobs:
  phpunit:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          php-version: "8.1"
          ini-values: memory_limit=-1
          extensions: sodium, fileinfo, redis

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"

      - name: "Run PHPUnit"
        run: composer test

  psalm:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          ini-values: memory_limit=-1
          extensions: sodium, fileinfo, redis

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"

      - name: "Run Psalm"
        run: composer psalm

  phpcs:
    name: "Code Style"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          ini-values: memory_limit=-1
          extensions: sodium, fileinfo, redis

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"

      - name: "Run PHPCS"
        run: composer cs-check
